export const STATUS = {
    UPDATE_ERROR_DETAIL: 'UPDATE_ERROR_DETAIL',
    UPDATE_LOGIN_STATE: 'UPDATE_LOGIN_STATE',
    UPDATE_REGISTER_STATE: 'UPDATE_REGISTER_STATE'
  }

export const USER = {
    REGISTER: 'REGISTER',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT'
  }